Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2023-07, with the labels that each got.

#72 feat: enable log prod
  helm/values-prod.yaml
Labels: size/small

#70 Chk 1694 fix deploy pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/deploy-pipelines.yml
Labels: size/small

#71 feat(CD): deploy on PR merge
  .devops/deploy-pipelines.yml
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yaml
  .github/workflows/deploy.yml
  README.md
Labels: skip-release

#74 fix(deploy-pipeline): prod manual approval depends on green api tests
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#75 Chk 1699 fix api test uat green
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#76 fix(deploy-pipeline): uat api test condition
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#77 fix(deploy-pipeline): uat api test condition
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#78 fix: pr extraction number from commit message
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, skip-release

#79 [CHK-1707] - feat(calculate-fees): add payment method description
  api-spec/api.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
Labels: size/small, chart-minor, minor

#73 [CHK-1590] feat(tracing): use OpenTelmetry agent instead of Elastic APM
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small
