Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2023-11, with the labels that each got.

#120 CHK-2087: feat: added UniqueId generation for orderId
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/utils/UniqueIdUtils.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/UniqueIdUtilsTests.java
Labels: size/small, chart-minor, minor

#123 [CHK 2096] feat: generate unique orderId with prefix and cache check
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/RedisConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/exception/UniqueIdGenerationException.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/UniqueIdDocument.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/UniqueIdTemplateWrapper.java
  src/main/java/it/pagopa/ecommerce/payment/methods/utils/UniqueIdUtils.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/UniqueIdUtilsTests.java
Labels: size/small, chart-minor, minor

#126 [CHK-2103] fix(npg): add error handling for NPG client in controller
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
Labels: size/small, patch, chart-patch

#128 Chk-2126: payment method with clientId
  api-spec/api.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java
  src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactory.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PaymentMethodDocument.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PaymentMethodRepository.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactoryTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: chart-minor, minor

#132 feat: Chk 2075 podAntiAffinity
  helm/values-prod.yaml
Labels: size/small, chart-minor, minor
