Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2023-08, with the labels that each got.

#81 fix: enable open telemetry log sending
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#80 feat(npg): [CHK-1782] add commons library
  .devops/code-review-pipelines.yml
  .env.example
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientTestConfig.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#82 [CHK-1782] refactor(env): rename env var `NPG_KEY` -> `NPG_API_KEY`
  .env.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/main/resources/application.properties
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#83 [CHK-1734] feat(api): add endpoint for creating form for a payment method
  api-spec/api.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
Labels: size/small, patch, chart-patch

#85 [CHK-1785] feat(npg): add session endpoint to retrieve form from NPG
  README.md
  api-spec/api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/PaymentMethodsApplication.java
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/OpenTelemetryConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/RedisConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/SessionUrlConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/converters/URIConverter.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java
  src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactory.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionDocument.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionsTemplateWrapper.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientTestConfig.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactoryTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
  src/test/resources/application.test.properties
Labels: size/large, patch, chart-patch

#87 fix(config): fix integer values into config maps to string values
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#86 feat(read card data): CHK-1817 added new endpoint for read card data by NPG
  api-spec/api.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: size/small, chart-minor, minor

#89 fix(helm value): fixed helm value npg variable for uat and prod
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#90 fix(helm value): fixed secret name for npg api key from npg-key to npg-api-key
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#91 feat(retrieve card data) CHK 1828 cache value
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/exception/SessionIdNotFoundException.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/CardDataDocument.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionDocument.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: size/small, chart-minor, minor

#92 [CHK-1787] feat(commons): update commons version
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientConfigTest.java
Labels: size/small, patch, chart-patch

#94 fix(configuration): CHK-1847 fixed npg uri configuration and problem into logic
  .env.example
  helm/values-dev.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
Labels: size/small, patch, chart-patch

#96 fix(dependency) added redis dependency
  pom.xml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch
