Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2023-10, with the labels that each got.

#113 chore(conf): [CHK-1901] - use uat GEC for dev env
  helm/values-dev.yaml
Labels: size/small, patch, chart-patch

#114 fix: increase initial delay
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#115 feat(test): [CHK-1999] add end-to-end-test after deploy
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#116 feat(deploy pipeline): CHK-1870 api tests for NPG
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
Labels: size/small, chart-minor, minor

#117 chore(deps): [CHK-2004] - update `commons` version to 0.26.0
  pom.xml
Labels: size/small, patch, chart-patch, 🤖 automatic, commons

#119 fix: increase prod limit
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small
