Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2023-09, with the labels that each got.

#95 feat(common): CHK-1833 update common lib to 0.21.0
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientConfigTest.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
Labels: size/small, chart-minor, minor

#93 [CHK-1836] feat(api): add endpoint to validate session with id and security token
  api-spec/api.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/exception/InvalidSessionException.java
  src/main/java/it/pagopa/ecommerce/payment/methods/exception/MismatchedSecurityTokenException.java
  src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionDocument.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: patch, chart-patch

#97 [CHK-1839] feat(sessions): add endpoint to associate NPG session to transaction id
  api-spec/api.yaml
  helm/values-dev.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/exception/SessionAlreadyAssociatedToTransaction.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: patch, chart-patch

#101 Chk 1871 fixed context path folder tests
  .devops/code-review-pipelines.yml
Labels: size/small, skip-release

#102 feat(deploy): increase CPU request and limit for dev environment
  helm/values-dev.yaml
Labels: size/small, patch, chart-patch

#99 [CHK-1856] fix: Make `getTransactionId` return transaction id encoded in base64
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
  src/test/resources/logback-spring.xml
Labels: size/small, patch, chart-patch

#108 feat(deps): update commons version
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientConfigTest.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
Labels: size/small, chart-minor, minor
