Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2024-05, with the labels that each got.

#188 fix(monitoring): correlation id for GET card data
  src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
Labels: size/small, patch, chart-patch

#190 feat(log): enable conf to configure log level
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: size/small, chart-minor, minor

#191 fix: add ndot conf for npg client
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
Labels: size/small, patch, chart-patch

#185 feat: beta version with dev refs
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#186 feat: [CHK-2795] Add payment methods v2 to support Cart
  .devops/code-review-pipelines.yml
  README.md
  api-spec/v1/api.yaml
  api-spec/v2/api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/BundleOptions.java
  src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/application/v2/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/client/AfmClient.java
  src/main/java/it/pagopa/ecommerce/payment/methods/config/WebClientsConfig.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/v1/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/v2/PaymentMethodsController.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/ecommerce/payment/methods/application/BundleOptionsTest.java
  src/test/java/it/pagopa/ecommerce/payment/methods/client/AfmClientTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/v1/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/controller/v2/PaymentMethodsControllerTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/v1/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/v2/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#184 feat: CHK-2625 add warmup
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/v1/PaymentMethodsController.java
  src/main/java/it/pagopa/ecommerce/payment/methods/controller/v2/PaymentMethodsController.java
  src/main/resources/application.properties
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#192 feat: handle beta version for notification url
  helm/values-dev.yaml
Labels: size/small, skip-release, ignore-for-release

#197 [CHK-2840] feat(method-management): add more values for method management
  api-spec/v1/api.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java
Labels: size/small, patch, chart-patch

#195 fix: ndots
  src/main/java/it/pagopa/ecommerce/payment/methods/config/WebClientsConfig.java
Labels: size/small, patch, chart-patch
