Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2024-07, with the labels that each got.

#202 [CHK-2887] feat(keepalive): add keepalive conf only for npg
  .env.example
  README.md
  gec-mock/Dockerfile.gec-mock
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientConfigTest.java
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#216 chore(helm): increase min replicas to 5
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#215 fix: update commons version for SATISPAY code
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java
Labels: size/small, chart-minor, minor
