Repository pagopa/pagopa-ecommerce-payment-methods-service, pull requests merged in 2024-11, with the labels that each got.

#232 [CHK-3496] add sorting policy to calculateFees method
  src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
  src/main/java/it/pagopa/ecommerce/payment/methods/application/v2/PaymentMethodService.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/v1/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/v2/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: size/large, chart-minor, minor

#233 fix: set right api test refs
  .devops/deploy-pipelines.yml
Labels: size/small, chart-patch, ignore-for-release

#236 feat: add random queryparam into return url
  src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
  src/test/java/it/pagopa/ecommerce/payment/methods/service/v1/PaymentMethodServiceTests.java
  src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java
Labels: size/small, chart-minor, minor

#235 fix(deploy): increase max surge
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch
